// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Detail } from "./Detail";

/**
 * A file stored by reference to an external provider-visible URI.
 *
 * This is used when a provider accepted the URI directly (for example Vertex
 * `gs://` or Gemini 2.5+ `https://`) and TensorZero never needed to fetch file
 * bytes. It deliberately does not pretend to be an object-storage pointer.
 */
export type StoredExternalFile = {
  url: string;
  mime_type: string | null;
  detail?: Detail;
  filename?: string;
};
